### ISSUE TITLE
Что-то ломает ютуб

### ISSUE THREAD

**Issue by gavrpsn** [1andrevich/Re-filter-lists#1]
Использую на микротике antifilter.network и download, с ними отлично работает ютуб.
Поднял еще ваш сервис и ютуб начинает штормить, что-то лишнее попадает в список.
Можно ютуб перенести в коммунити лист?

**Comment by 1andrevich** [comment]
Спасибо за обратную связь, ютуб проверял на нескольких девайсах в разных провайдерских сетях, перепроверю. У вас совсем ютуб не работает или иногда открывает через VPN?

**Comment by gavrpsn** [comment]
Открывается, но не загружаются настройки и видео прерывается перебирая снижение качества, как в принципе это сейчас без впн работает.
Ютуб на смарт тв самсунг

**Comment by 1andrevich** [comment]
Проблему нашёл (в OONI), сейчас готовлю новый релиз с исправлением ютуба

**Comment by 1andrevich** [comment]
Список на BGP обновил, сейчас готовлю релиз новых списков для V2Fly, Sing-Box

**Comment by 1andrevich** [comment]
Все файлы обновил

**Comment by gavrpsn** [comment]
Работает, благодарю за решение!
