### ISSUE TITLE
Youtube и Discord в domains_all

### ISSUE THREAD

**Issue by Eptiy** [1andrevich/Re-filter-lists#11]
Для начала уточню: я не уверен в том, что использую списки правильно. Так как в билдах запрета идут либо слишком большие, либо слишком маленькие списки, решил попробовать этот.

Как выяснилось, список доменов ютуба, идущий в комплекте с билдами позволяет обойти блокировку, в то время как список domains_all - нет. При добавлении в него доменов из этого списка ютуб начинает исправно работать.

С дискордом похожая ситуация. С domains_all не отправляются медиа-файлы. Нужно добавлять больше доменов.

Вот список доменов, которые я добавил, чтобы всё работало. Только не могу сказать, нужны ли все из них.
[domains_yt+ds.txt](https://github.com/user-attachments/files/17381579/domains_yt%2Bds.txt)

**Comment by Eptiy** [comment]
Обновил инфу по вопросу.

**Comment by 1andrevich** [comment]
Добавил в 4 релиз
