### ISSUE TITLE
Не работает релиз 14го числа

### ISSUE THREAD

**Issue by gelato** [1andrevich/Re-filter-lists#120]
xray пишет Failed to start: main: failed to load config files: [/etc/v2raya/config.json] > infra/conf: invalid field rule > infra/conf: failed to load GeoIP: refilter > infra/conf: code not found in geoip.dat: REFILTER
и не запускается.
Откатился на релиз 12го числа и все задышало.

**Comment by 1andrevich** [comment]
Попробуйте файл заново скачать

**Comment by gelato** [comment]
Да, сейчас все ок, спасибо
