### ISSUE TITLE
Instagram не грузит медиа

### ISSUE THREAD

**Issue by tunivi** [1andrevich/Re-filter-lists#17]
Добавил geosite.dat и geoip.dat из последнего релиза в приложение V2rayNG на Android. Прописал правила маршрутизации, как указано в Readme. Всё работает, заблокированные ресурсы открываются, а незаблокированные идут напрямую. Но есть проблема с инстой - совсем не грузятся фото и видео. Причём сама лента обновляется, текст отлично виден, но медиа - нет.

**Comment by 1andrevich** [comment]
Инстаграм проверю, спасибо что обозначили проблему

**Comment by tunivi** [comment]
Я думаю, что дело в домене cdninstagram.com
В ваших списках эта CDN указана с различными поддоменами. Если оставить в списке только адрес cdninstagram.com, то наверняка всё заработает. На антизапрете так в своё время делали.

**Comment by 1andrevich** [comment]
Добавил в 4 релиз
