### ISSUE TITLE
Tidal и Adobe

### ISSUE THREAD

**Issue by AlexanderChurbanov** [1andrevich/Re-filter-lists#20]
Добавьте, пожалуйста, сети Adobe и Tidal они для РФ не работают

**Comment by 1andrevich** [comment]
Если у вас есть домены, диапазоны IP Adobe и Tidal прошу поделится, не изучал вопрос пока

**Comment by AlexanderChurbanov** [comment]
> Если у вас есть домены, диапазоны IP Adobe и Tidal прошу поделится, не изучал вопрос пока

Вы знаете, я у себя в Mikrotik делаю так, вместе с поддонами: 
/ip dns static add address-list=dns-resolver-cache-list forward-to=cloudflare-dns.com match-subdomain=yes name=tidal.com type=FWD
/ip dns static add address-list=dns-resolver-cache-list forward-to=cloudflare-dns.com match-subdomain=yes name=adobe.com type=FWD
/ip dns staticadd address-list=dns-resolver-cache-list forward-to=cloudflare-dns.com match-subdomain=yes name=adobeereg.com type=FWD
/ip dns static add address-list=dns-resolver-cache-list forward-to=cloudflare-dns.com match-subdomain=yes name=adobelogin.com type=FWD

то есть, по основным доменам + субдомены. Вам такой вариант не подойдет ? Субдоменов то много, они CDN используют
