### ISSUE TITLE
Списки с поддержкой ECH  и без

### ISSUE THREAD

**Issue by dKenGuru** [1andrevich/Re-filter-lists#26]
Сделать вариации списков с поддержкой ECH и без.
https://ntc.party/t/%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-esni-encrypted-sni-%D0%B2-%D1%80%D0%BE%D1%81%D1%81%D0%B8%D0%B8/68/58

**Comment by Akiyamov** [comment]
Сделал пока для себя простой скрипт, который по большей мере нужен чтоб использовать в sing-box. [Репозиторий](https://github.com/Akiyamov/singbox-ech-list)

**Comment by dKenGuru** [comment]
Нужно в актуальном варианте srs. Не json.

**Comment by Akiyamov** [comment]
Я пока залил и ci в дженкинсе идет. То, что должно быть rule-set'ом знаю. Пока еще посмотрю как сделать через питон, чтоб можно было в этот репозиторий что-то добавить, раз тут везде питон

**Comment by dKenGuru** [comment]
Смотрю уже появился вариант в srs.
Надо бы как-то все в один список сделать. А то 100500 списков и собери из них свой сам.

**Comment by Akiyamov** [comment]
В один список? Сделать типа один спиоск для srs или как? Я просто собираю оп файлам отдельно чтоб потом использовать сразу. Хотите чтоб был один файл или как? Можно еще json для srs грузить, чтоб потом можно ручками докидывать все

**Comment by dKenGuru** [comment]
Нее. Я к тому, чтобы это было не отдельным репо, а тут, отдельным вариантом.
Получается всем надо по лесу ходить и грибы выискивать.
Если бы не тикет тут и тема на форуме, то никто бы и не нашел.

**Comment by Akiyamov** [comment]
А. Ну это уже автора ждать

**Comment by Akiyamov** [comment]
[Все.](https://ntc.party/t/%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B7%D0%B0%D0%BC%D0%B5%D0%B4%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-ech-cloudflare/12732/109)
Картинки из Ералаша не хватает

**Comment by dKenGuru** [comment]
Частично да. Но если домен внести в обход, то FF работает. А вот Edge и последние Хром и ко уже нет (причем так и не понял куда они лезут и как для сверки). Хотя если им насильно прописать днс, то тоже работает, но ECH тесты не проходит.

**Comment by Eptiy** [comment]
Внёс cloudflare-ech.com в обход. В браузерах Edge, Yandex и Firefox настроил DoH. Во всех проверка на ECH прошла, все 4 галки стоят. Сайты, которые по словам людей не открываются с ECH (из-за его блокировки), открываются исправно. Помимо прочего, внесение домена в обход пофиксило пару отвалившихся на днях штук в дс. В общем, проще все блоки теперь обходить сразу, включая весь кластер ech-сайтов.

**Comment by 1andrevich** [comment]
cloudflare-ech.com в списки добавлен, в отдельном списке с ECH в рамках проекта смысла пока не вижу
