### ISSUE TITLE
v2raya

### ISSUE THREAD

**Issue by kozhini** [1andrevich/Re-filter-lists#3]
при использовании  re-filter .dat ломается работа v2raya, с настройками из [этой статьи](https://habr.com/ru/articles/773696/)
при возврате на [antifilter-domain](https://github.com/1andrevich/antifilter-domain) и [antifilter-geoip](https://github.com/1andrevich/antifilter-geoip) всё приходит в норму. полагаю что-то с RoutingA
лог
```
2024/10/14 04:16:08.755  [I] [io.go:431]  Failed to start: main: failed to load config files: [/etc/v2raya/config.json] > infra/conf: invalid field rule > infra/conf: failed to load GeoIP: antifilter > infra/conf: code not found in geoip.dat: ANTIFILTER
2024/10/14 04:16:09.188  [W] [asm_arm64.s:1223]  v2ray-core: exit status 23
```

**Comment by 1andrevich** [comment]
Спасибо что написали, для этих списков нужны иные настройки RoutingA:
`default: direct`
`ip(geoip:refilter)->proxy`
`domain(ext:"LoyalsoldierSite.dat:refilter")->proxy`
Дополню README в ближайшее время

**Comment by kozhini** [comment]
спасибо, v2raya теперь запускается и работает, но перестали открываться закрытые разделы на 4pda)
