### ISSUE TITLE
SoundCloud и X (Twitter)

### ISSUE THREAD

**Issue by Vvorcun** [1andrevich/Re-filter-lists#32]
SoundCloud и X (Twitter) не открываются

**Comment by dKenGuru** [comment]
Sound да. Твиттер работает исправно.

**Comment by Eptiy** [comment]
У меня оба работают, по доменам.

**Comment by dKenGuru** [comment]
> У меня оба работают, по доменам.

Да, верно. Нашел в чем косяк.
Любые правила из стоковых (geoip, ACL) по Amazon IP конфликтуют с текущим списком.

**Comment by Ferbez** [comment]
> У меня оба работают, по доменам.

К сожалению не имею возможности настроить у себя сейчас фильтрацию по доменам, использую `ipsum.lst` и с ним ни SoundCloud, ни X (Twitter) не работают
