### ISSUE TITLE
GeForce Experience

### ISSUE THREAD

**Issue by xRomZak** [1andrevich/Re-filter-lists#34]
Заметил сегодня, что перестали дрова для Nvidia загружаться через GeForce Experience c ru ip. Пишет вечный retrying. Врубил vpn и пошла загрузка. Значит и эти товарищи "созрели" до блокировок.

**Comment by dKenGuru** [comment]
уже не актуально

**Comment by 1andrevich** [comment]
Добавил в 6 релизе

**Comment by dKenGuru** [comment]
А зачем? Это была проблема с их стороны. Ее уже нет.
