### ISSUE TITLE
pagead2.googlesyndication.com

### ISSUE THREAD

**Issue by shikulja** [1andrevich/Re-filter-lists#36]
Просто случайно нашел

Не открывался https://ru.riotpixels.com/games/exographer/screenshots/
помог резолвинг адресов
`  188.114.97.3 riotpixels.com ru.riotpixels.com en.riotpixels.com static.riotpixels.com auth.riotpixels.com s01.riotpixels.com # riotpixels`

но сайт все еще долго думал и крутил бублик, оказалось еще один хост давал тупняк
  #  0.0.0.0       pagead2.googlesyndication.com                        # Google Ad
я занулил его, мне ок, но если добавить в список dpi то он нормально прогружается тоже.

проверка резолва с помощью IPfinder (by Ory)
с обходом блокировок
```
IP: 173.194.221.157 
Ping: YES                       Data    Data    SSL     Re-     HTTP    Exit            Response
Mode                    Time    sent    get     check   direct  Ver.    code            code
TLS 1.2                 0.066s  YES     YES     OK      NO      HTTP/2  0 OK            404 Not Found
TLS 1.3                 0.064s  YES     YES     OK      NO      HTTP/2  0 OK            404 Not Found
QUIC                    0.263s  YES     YES     OK      NO      HTTP/2  0 OK            404 Not Found
TLS 1.2  fake SNI       0.084s  YES     YES     SKIP    SKIP    HTTP/2  0 OK            404 Not Found
TLS 1.3  fake SNI       0.044s  YES     YES     SKIP    SKIP    HTTP/2  0 OK            404 Not Found
QUIC     fake SNI       0.244s  YES     YES     SKIP    SKIP    HTTP/2  0 OK            404 Not Found
```

без обхода блокировок
```
IP: 142.250.9.157 
Ping: YES                       Data    Data    SSL     Re-     HTTP    Exit            Response
Mode                    Time    sent    get     check   direct  Ver.    code            code
TLS 1.2                 FAIL    -       -       -       -       -       28 TIMEOUT      -
TLS 1.3                 FAIL    -       -       -       -       -       28 TIMEOUT      -
QUIC                    FAIL    -       -       -       -       -       28 TIMEOUT      -
TLS 1.2  fake SNI       0.146s  YES     YES     SKIP    SKIP    HTTP/2  0 OK            404 Not Found
TLS 1.3  fake SNI       0.153s  YES     YES     SKIP    SKIP    HTTP/2  0 OK            404 Not Found
QUIC     fake SNI       0.113s  YES     YES     SKIP    SKIP    QUIC    0 OK            404 Not Found
```

это как я думаю рекламный хост гугла который ушел из рф. но похоже у некоторых он висит, и не дает нормально прогружатся.

**Comment by dKenGuru** [comment]
А точно ни какая резалка рекламы, кук и т.д?
Вот попробовал без заграничного сервера и все прекрасно открывается.

**Comment by shikulja** [comment]
Блокировщики обычно выглядят так, это точно не они.
       GET https://mc.yandex.ru/metrika/watch.js net::ERR_BLOCKED_BY_CLIENT
Очень странно, но реклама гугла на сайте пропала, может среагировал кто-то.

Через пару дней закрою, если не смогу выловить на скрин.

**Comment by shikulja** [comment]
@dKenGuru 
<img width="418" alt="{3776B647-B7E4-44A7-B2B1-5DA23DE5E7B4}" src="https://github.com/user-attachments/assets/e1c6911b-b7a7-4086-b72f-17052dccc191">

Раньше у меня появлялся постоянно, с тайм-аутом. Этот раз выловил случайно, причем на разных браузерах искал.

**Comment by dKenGuru** [comment]
У них какой-то крайне странный сайт. В плане кода.
Один провайдер. Через смартфон, браузер FF, включен Karing и списки правил. Открывается сайт без проблем.
Через комп, тот же клиент и 1в1 настройки, браузер FF. Не открывается.

**Comment by shikulja** [comment]
Да сайт странный. С ним я уже давно мучался. Поэтому уже воевать начал.
Хоть pagead2.googlesyndication.com и прикручен у них, но это похоже проблема гугла, что он таймаутится, и крутит сайт в прогрузке.

**Comment by dKenGuru** [comment]
https://riotpixels.com/ открылся в браузере.
У сайта какая-то хрень с TLS и стабильностью. Один раз прогрузился и дальше нормально работает на субдоменах.

**Comment by shikulja** [comment]
У него несколько ip адресов
104.21.19.78
172.67.185.167
188.114.97.1
188.114.96.1
первые два основные мертвые напрочь, потом скорее всего перекидывает на другие, может быть DNS.

**Comment by dKenGuru** [comment]
Гугл и т.д. тут не виноваты. Проблемы с TLS и сайтом должны решать сами владельцы сайта.

**Comment by shikulja** [comment]
Так и не в сайте дело, я его поддомены уже переадресовал
  188.114.97.3 riotpixels.com ru.riotpixels.com en.riotpixels.com static.riotpixels.com auth.riotpixels.com s01.riotpixels.com # riotpixels
так он работает и открывается с ноги, проблем нет.

Но, он не прогружается до конца, раньше постоянно, сейчас реже, и проблема в домене гугла
pagead2.googlesyndication.com который в таймауте.
если добавить в список DPI этот домен, то он оживает и возвращает 404 без таймаута.
(либо просто занулить как я, так как его все равно в списках пока нет)

**Comment by shikulja** [comment]
Да сайт беда, но почему то информация по играм у них обновляется. И ссылки на скриншоты фитгерл как раз на них.

Но я отчет написал не из-за них, а из-за pagead2.googlesyndication.com
просто если он мешает прогрузки сайта. То он может выстрелить еще где-нибудь и тоже крутить страницы в прогрузе.
(Может существует какой-нибудь сервис для отслеживания отсылок на этот домен. Но я не в курсе.)

**Comment by shikulja** [comment]
оказывается по теме много гуглится
https://www.reddit.com/r/jailbreak/comments/2qxiqn/why_is_pagead2googlesyndicationcom_still/
https://support.google.com/google-ads/thread/1714045/%D0%98%D1%81%D1%82%D0%BE%D1%87%D0%BD%D0%B8%D0%BA-pagead2-googlesyndication-com-%D0%B2-%D0%BE%D1%82%D1%87%D0%B5%D1%82%D0%B0%D1%85-google?hl=ru

https://community.brave.com/t/blocking-youtube-ads-without-adblockers-brave-shields-or-3rd-party-softwares-full-guide-on-how-to-supercharge-your-brave-browsers-yt-experience/511336
https://github.com/confirmedcode/lockdown-ios/issues/16
https://www.webmasterworld.com/google_adsense/5083807.htm
https://discourse.pi-hole.net/t/how-to-block-google-ads-including-youtube-ads/54255/2
https://stackoverflow.com/questions/14304794/google-mobile-ads-url-adserver

**Comment by shikulja** [comment]
Проблема только на клаудфлер днс. На остальных блочится адблоком.
