### ISSUE TITLE
rutor

### ISSUE THREAD

**Issue by butaford** [1andrevich/Re-filter-lists#41]
Приветствую. В списках пропал rutor.info rutor.is

**Comment by dKenGuru** [comment]
Есть rutor.org. Зачем 100500 одно и того же?

**Comment by butaford** [comment]
> Есть rutor.org. Зачем 100500 одно и того же?

Вы сначала сравните и проанализируйте, что не одно и тоже...

**Comment by dKenGuru** [comment]
> Вы сначала сравните и проанализируйте, что не одно и тоже...
В смысле? Это одно и тоже https://wikireality.ru/wiki/Rutor.org

**Comment by butaford** [comment]
rutor.org это попрошайки, с ворованными раздачами с rutor.lib, rutor.is, rutor.info. Посмотрите на их раздачи с нулевыми пирами и сидерами.

**Comment by butaford** [comment]
> > Вы сначала сравните и проанализируйте, что не одно и тоже...
> > В смысле? Это одно и тоже https://wikireality.ru/wiki/Rutor.org
Я тоже пооперирую ссылками
https://ru.m.wikinews.org/wiki/%D0%9A%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D0%B8%D1%8F:Rutor.org

**Comment by Jipok** [comment]
rutor.info в списке нет

**Comment by cat5e-inv** [comment]
Комрад прав, добавьте пожалуйста rutor.info rutor.is
