### ISSUE TITLE
Домены

### ISSUE THREAD

**Issue by zxc-rv** [1andrevich/Re-filter-lists#45]
quora.com
software-static.download.prss.microsoft.com (для скачки винды)
cdn.betterttv.net (смайлы твича некоторые не грузятся)
stable.dl2.discordapp.net (для скачки дискорд клиента с офф сайта)
streamable.com

**Comment by TyroSpy** [comment]
yt4.ggpht.com

**Comment by 1andrevich** [comment]
https://github.com/1andrevich/Re-filter-lists/releases/tag/11112024

**Comment by Mel0ne** [comment]
В список был добавлен discordapp.net, а не stable.dl2.discordapp.net. Первый не имеет DNS записей, поэтому ни скачивание приложения с сайта, ни обновление установленного клиента не происходит. Нужен именно stable.dl2.discordapp.net

**Comment by 1andrevich** [comment]
Спасибо за разъяснение, добавлю

**Comment by ktulhu2000** [comment]
а можно вопрос. конфиг из readme работает на шлюзе RPi, и в google поиск ходит через впн (( 1. это так и должно быть? 2.  можно как-то исправить? thnx

**Comment by 1andrevich** [comment]
Ну это к сожалению связано с блокировкой YouTube, IP адреса YouTube и Google все принадлежат к ASN Google и она подтягивается целиком

**Comment by 1andrevich** [comment]
> В список был добавлен discordapp.net, а не stable.dl2.discordapp.net. Первый не имеет DNS записей, поэтому ни скачивание приложения с сайта, ни обновление установленного клиента не происходит. Нужен именно stable.dl2.discordapp.net

stable.dl2.discordapp.net в списке присутствует
