### ISSUE TITLE
Использовать LF в качестве перевода строки вместо CRLF

### ISSUE THREAD

**Issue by maksimkurb** [1andrevich/Re-filter-lists#47]
Добрый день. Сейчас в некоторых файлах списков в качестве перевода строки используется CRLF (`\r\n`).
Некоторые инструменты некорректно обрабатывают файлы с таким переводом строки.

В частности, ruantiblock для OpenWRT не умеет обрабатывать файлы с CRLF: https://github.com/gSpotx2f/ruantiblock_openwrt/issues/94

Можно ли исправить переносы для следующих файлов с CRLF на LF?
1. community.lst
2. domains_all.lst
3. ipsum.lst

Недавно в GIT появился удобный инструмент для того, чтобы заменить переносы строк `--renormalize`: https://stackoverflow.com/a/47580886

Спасибо!

**Comment by 1andrevich** [comment]
https://github.com/1andrevich/Re-filter-lists/releases/tag/11112024
