### ISSUE TITLE
connectivitycheck.gstatic.com

### ISSUE THREAD

**Issue by EikeiDev** [1andrevich/Re-filter-lists#48]
Не знаю почему, но у провайдера находится в замедлении, возможно РКН задел вместе с YouTube(

time.google.com
connectivitycheck.gstatic.com

**Comment by dKenGuru** [comment]
Если это частные локальные вещи, то такое проще самому сделать в свое собственное правило, список, чем вносить все частные случаи и хотелки в глобальный список.
