### ISSUE TITLE
autodesk.com

### ISSUE THREAD

**Issue by KyuremBoG** [1andrevich/Re-filter-lists#52]
День добрый, можно ли добавить домены autodesk.com? Чтобы была возможность работать с autodesk fusion 360

**Comment by Eptiy** [comment]
Автодеск ведь заблокирован не силами ркн, а своими собственными, если я не ошибаюсь. Там поможет только впн.

**Comment by KyuremBoG** [comment]
> Автодеск ведь заблокирован не силами ркн, а своими собственными, если я не ошибаюсь. Там поможет только впн.
Ну я понимаю, я же как раз этот список для vpn и использую, все из этого списка по vpn у меня и идет. Как я понял, ибо не внимательно прочитал, это список только заблокированных сайтов ркн. Поэтому чего то может и не быть.
