### ISSUE TITLE
linkedin

### ISSUE THREAD

**Issue by harmakit** [1andrevich/Re-filter-lists#53]
не работает linkedin :(
подключил список через bird (165.22.127.207 as 65412)
причем вижу, что в domains_all домен присутствует

**Comment by slavaponomareveezee** [comment]
> не работает linkedin :( подключил список через bird (165.22.127.207 as 65412) причем вижу, что в domains_all домен присутствует


Хм, Xray из списка domains_all не открывает только linkedin.cn, остальные linkedin влёт

**Comment by harmakit** [comment]
тогда, думаю, у меня локальная проблема. закрываю тикет
