### ISSUE TITLE
Ещё сайты в список(f95zone.to и y2mate.com)

### ISSUE THREAD

**Issue by abubaca4** [1andrevich/Re-filter-lists#54]
Сам f95zone.to открывается, но https://attachments.f95zone.to нет. Стоит добавить
y2mate.com не открывается

**Comment by 1andrevich** [comment]
y2mate.com в списке доменов есть, attachments это поддомен, должен открываться

**Comment by abubaca4** [comment]
> y2mate.com в списке доменов есть, attachments это поддомен, должен открываться

Может быть тогда какая то проблема в списках sing-box? Потому что у меня y2mate.com улетает на заглушку провайдера, https версия не открывается с ошибкой PR_END_OF_FILE_ERROR. С attachments.f95zone.to тоже самое.(хотя основной сайт открывается). При этом с флибустой, рутрекером и множеством других сайтов проблем нет. Учитывая что y2mate.com переадресует на www.y2mate.com это вполне может быть проблемой с работой поддоменов. Если я вручную добавляю в конфиг sing-box домены через "domain_suffix" то они начинают работать.
```
{
"domain_suffix": [
                    "h-chan.me",
                    "hentaichan.live"
                ],
                "outbound": "warp"
                }
```
С https://github.com/savely-krasovsky/antizapret-sing-box таких проблем нет но там файл сильно жирнее
