### ISSUE TITLE
code not found in geoip.dat: REFILTER

### ISSUE THREAD

**Issue by 13thRaven** [1andrevich/Re-filter-lists#57]
Доброго, через некоторое время v2raya падает и не запускается вот с такой ошибкой 
Failed to start: main: failed to load config files: [/etc/v2raya/config.json] > infra/conf: invalid field rule > infra/conf: failed to load GeoIP: refilter > infra/conf: code not found in geoip.dat: REFILTER
повторное скачивание Вашего geoipdat не помогает, в чем может быть проблема?

**Comment by 1andrevich** [comment]
Ошибка с большой долей вероятности в вашей конфигурации RoutingA, с этим вопром лучше на [Хабр](https://habr.com/ru/articles/773696/)
