### ISSUE TITLE
rezka

### ISSUE THREAD

**Issue by Goblin-Mini** [1andrevich/Re-filter-lists#60]
До сих пор не добавлен основной домен хдрезки rezka.ag,добавьте его наконец. Миллион зеркал которые  зеркала основного домена есть а его нет.

**Comment by 1andrevich** [comment]
Добавлено в [Release 9](https://github.com/1andrevich/Re-filter-lists/releases/tag/04122024)

**Comment by Goblin-Mini** [comment]
Спасибо.
