### ISSUE TITLE
www.citrix.com

### ISSUE THREAD

**Issue by shipiguzeff** [1andrevich/Re-filter-lists#61]
Приветствую!
Нехватает адреса для www.citrix.com 23.207.103.177

**Comment by 1andrevich** [comment]
Добавлено в [Release 9](https://github.com/1andrevich/Re-filter-lists/releases/tag/04122024)

**Comment by Jipok** [comment]
@1andrevich м.б. создать отдельный issue для добавление новых сайтов?

**Comment by Jipok** [comment]
В общем, я не стал плодить ещё один isse.
htmgo.dev не работает, его бы в списочек внести
