### ISSUE TITLE
Kinopub и hdrezka отсутствуют в списках

### ISSUE THREAD

**Issue by Gleb6882** [1andrevich/Re-filter-lists#7]
UPD: Увидел закрытый Issue по Hdrezka, про неё уже не актуально.
Остаётся только кинопаб:
![image](https://github.com/user-attachments/assets/1db712e3-ce8d-470a-b521-db059bb4cdf0)

Сайты https://kino.pub и https://hdrezka.ag отсутствуют в списках, хотя явно заблокированы РКН (проверить можно тут https://blocklist.rkn.gov.ru/#anchor)
Возможно неправильно отфильтровались?
![hdrezka](https://github.com/user-attachments/assets/bd6d862a-66d0-443b-9ed5-4ddc64bf9de3)
![kinopub](https://github.com/user-attachments/assets/69663414-f433-4887-9df3-39b369bf56ef)

**Comment by elsorcier** [comment]
Так же https://rezka.ag

**Comment by undfndusr** [comment]
Кроме самой hdrezka.ag нужно добавить static.hdrezka.ag (превьюшки к фильмам) 
А также домен, с которого идет видеопоток - voidboost.cc
И еще несколько поддоменов:
- stream.voidboost.cc
- fingerium.stream.voidboost.cc (360p)
- ununbium.stream.voidboost.cc (480p)
- atomic.stream.voidboost.cc (720p)
- ranger.stream.voidboost.cc (1080p)

**Comment by PentiumB** [comment]
zelenka.guru так-же. Как-то много чего популярного нет

**Comment by 1andrevich** [comment]
Добавлено в 4 релизе
